# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\input_forecasting_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 311)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setBaseSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.BtnChoose = QtWidgets.QPushButton(self.groupBox)
        self.BtnChoose.setObjectName("BtnChoose")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.BtnChoose)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.TxTemp = QtWidgets.QLineEdit(self.groupBox)
        self.TxTemp.setObjectName("TxTemp")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.TxTemp)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.TxWind = QtWidgets.QLineEdit(self.groupBox)
        self.TxWind.setObjectName("TxWind")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.TxWind)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.TxDirection = QtWidgets.QLineEdit(self.groupBox)
        self.TxDirection.setObjectName("TxDirection")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.TxDirection)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.TxHumidity = QtWidgets.QLineEdit(self.groupBox)
        self.TxHumidity.setObjectName("TxHumidity")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.TxHumidity)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.TxBarometer = QtWidgets.QLineEdit(self.groupBox)
        self.TxBarometer.setObjectName("TxBarometer")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.TxBarometer)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.TbResult = QtWidgets.QTableView(Dialog)
        self.TbResult.setObjectName("TbResult")
        self.gridLayout.addWidget(self.TbResult, 0, 1, 2, 1)
        self.BtnBox = QtWidgets.QDialogButtonBox(Dialog)
        self.BtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.BtnBox.setObjectName("BtnBox")
        self.gridLayout.addWidget(self.BtnBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Forecasting"))
        self.groupBox.setTitle(_translate("Dialog", "Input Data"))
        self.label.setText(_translate("Dialog", "Model"))
        self.BtnChoose.setText(_translate("Dialog", "Choose"))
        self.label_2.setText(_translate("Dialog", "Temperature (°C)"))
        self.label_3.setText(_translate("Dialog", "Wind (km/h)"))
        self.label_4.setText(_translate("Dialog", "Direction"))
        self.label_5.setText(_translate("Dialog", "Humidity"))
        self.label_6.setText(_translate("Dialog", "Barometer (mbar)"))
