# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/input_url_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.LUrlScraping = QtWidgets.QLineEdit(self.groupBox)
        self.LUrlScraping.setObjectName("LUrlScraping")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LUrlScraping)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.LLocationScraping = QtWidgets.QLineEdit(self.groupBox)
        self.LLocationScraping.setObjectName("LLocationScraping")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LLocationScraping)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.LNameScraping = QtWidgets.QLineEdit(self.groupBox)
        self.LNameScraping.setObjectName("LNameScraping")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LNameScraping)
        self.verticalLayout.addLayout(self.formLayout)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.BtnBox = QtWidgets.QDialogButtonBox(Dialog)
        self.BtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.BtnBox.setObjectName("BtnBox")
        self.gridLayout.addWidget(self.BtnBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Data Scraping"))
        self.groupBox.setTitle(_translate("Dialog", "Insert URL"))
        self.label_2.setText(_translate("Dialog", "URL"))
        self.label_3.setText(_translate("Dialog", "Location"))
        self.label_4.setText(_translate("Dialog", "File name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
